#!/bin/bash

#SBATCH --job-name=MACS2
#SBATCH --partition=basic
#SBATCH --cpus-per-task=1
#SBATCH --mem=35G
#SBATCH --output=depth-%j.out
#SBATCH --error=depth-%j.err
#SBATCH --time=00:30:00

module load macs3/

chip=$1
input=$2
out=$3

macs3 callpeak -t $chip -c $input -f BAMPE -g 2700000000 -n $out -p 1e-5 --keep-dup all

############### without input #############
macs3 callpeak -t $chip   -f BAMPE -g 2700000000 -n $out -p 1e-7 --keep-dup all --slocal 1000 --shift 100 --nolambda
